#!/usr/bin/env bash
if [[ "$OSTYPE" == "darwin"* ]] && type reattach-to-user-namespace >/dev/null 2>&1; then
  # macos clipboard integration
  tmux set-option -g default-command "reattach-to-user-namespace -l $SHELL"
  # true color support in iterm2
  tmux set-option -ga terminal-overrides ",xterm-256color:Tc"
fi
